[project]
name = "my_service"
version = "0.1.0"
description = "ML Pro project"
requires-python=">=3.11, <3.13"

dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "pydantic-settings",
    "pandas",
    "scikit-learn",
    "joblib",
    "psycopg[binary]",
    "numpy",
    "torch",
]

[dependency-groups]
dev = [
    "pytest",
    "httpx",
    "locust",
    "ruff",
    "ipykernel",
]

[build-system]
requires = ["uv_build>=0.10,<0.11"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "my_service"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"
